# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9ea60417649910523df353fb73bf4ee85b9686b9db54aa4ead23614321977287734e2f5cae88c41e9e7420158dbee42c310fb372b41caefe857c41e9f0663c30

test:
  secret_key_base: 07c4511f4285b801feaf26eea8aaa0963cfd2aa0e6046a5316f78550a11a27ba2a069b19e5778c0cc0f7e2f3efa45b35d8c32d5df07eb719998d9f8c09e967e9

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
